package taxandrun.model.event;

public enum GameEventType {
    POSTS_REACHED, TAX_COLLECTION_RESOLVED, DAY_STARTED, NIGHT_STARTED, WORK_REQUESTED, WORK_PERFORMED,
    BOSS_WARNING, BOSS_CHASE_STARTED, TAX_COLLECTION_REQUESTED,
    TAX_PAYMENT_SUCCEEDED, TAX_EVASION_STARTED, TAX_COLLECTOR_CHASE_STARTED
}
